server: 
  port: 8090
#뷰
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource: #바이바티스
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://finalproject.cf15puxifxqe.ap-northeast-2.rds.amazonaws.com:3306/finaldb?characterEncoding=utf-8
    username: root
    password: root1234


  devtools: #자동실행
    livereload:
      enabled: true


  #servlet:
    #multipart:
      #file-size-threshold: 10MB
      #location: /Users/yunri/Desktop/finalTeamProject/Petopia/src/main/webapp/upload/review
      #max-file-size: 100MB
      #max-request-size: 100MB
        
mybatis:
  type-aliases-package: com.campus.myapp.vo #mybatis에서 패키지 생략 할 수 있도록 설정
  mapper-locations: mapper/*Mapper.xml #쿼리문 경로 지정x  